[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "image/png"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "image/x-icon"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200