[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=0"
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=0"
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/apple-touch-icon.png"
  [headers.values]
    Cache-Control = "public, max-age=0"
    Content-Type = "image/png"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200