[[headers]]
  for = "/favicons/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/favicons/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/favicons/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200