[[headers]]
  for = "/favicons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/favicons/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/favicons/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/favicons/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

# Handle root favicon.ico requests
[[redirects]]
  from = "/favicon.ico"
  to = "/favicons/favicon.ico"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200