[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "image/png"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200